### PR TITLE
Add hardware scripts

### PR DESCRIPTION
**Pull request by mac-kan**
Adds hardware scripts for EL3311, EL3314-0010, EL3314-0020, EL3314-0030 and EL3318.

### CODE REVIEW

**Comment by javicereijo** [comment]
Looks good to me. @mac-kan have you checked the ECMC_EC_PRODUCT_ID s in the ESI xml-files as Anders proposed?

**Review by cdn-lnk — APPROVED** [review]
Hi @mac-kan,

- I removed the EL3314-0090.substitutions file since it looks like it has some kind of interface with TwinSAFE.
- I also added a fix related to ECMC_EGU, ECMC_PREC, ECMC_AXISFIELDINIT and ECMC_AXISCONFIG.

Everything else looks good.
Thanks.

**Comment by mac-kan** [comment]
@javicereijo Thanks for checking!

I checked the xml-files in the TwinCAT folder. However, I did not find any entry for either EL3314-0020 or EL3314-0030. We are assuming they are the same, which should be consistent with the remaining entries of EL3314-XXXX.

However, also in the EL33xx.xml file, me and Carlos found a small difference between the EL3314 and the EL3314-00XX:
EL3314:               xcf23052
EL3314-0002:     x0cf23052   (There is an extra 0 here)
EL3314-0010:     xcf23052

We've sent a mail to Anders asking him about it.

**Review by cdn-lnk — APPROVED** [review]

**Comment by javicereijo** [comment]
Everything seems to be ok!

**Pull request merged**
